export const MENUITEMS = [
  {
    menutitle: "MAIN",
    role: ["Super Admin", "Editor", "Property Manager", "User"],
  },

  {
    path: `${import.meta.env.BASE_URL}dashboard`,
    title: "Dashboard",
    icon: "fe-home",
    type: "link",
    active: false,
    selected: false,
    dirchange: false,
    role: ["Super Admin", "Editor", "Property Manager", "User"],
  },

  {
    menutitle: "Pages",
    role: ["Super Admin", "Editor", "Property Manager", "User"],
  },
  {
    title: "Users",
    icon: "fe-users",
    type: "sub",
    menusub: true,
    active: false,
    selected: false,
    dirchange: false,
    role: ["Super Admin"],
    children: [
      {
        path: `/dashboard/user`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "User List",
      },
      {
        path: `/dashboard/user/create`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Create User",
      },
    ],
  },
  {
    title: "Status",
    icon: "fe-bar-chart",
    type: "sub",
    menusub: true,
    active: false,
    selected: false,
    dirchange: false,
    role: ["Super Admin", "Editor"],
    children: [
      {
        path: `/dashboard/status`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Status List",
      },
      {
        path: `/dashboard/status/create`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Create Status",
      },
    ],
  },
  {
    title: "Course",
    icon: "fe-cpu",
    type: "sub",
    menusub: true,
    active: false,
    selected: false,
    role: ["Super Admin", "Editor"],
    dirchange: false,
    children: [
      {
        path: `/dashboard/course`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Course List",
      },
      {
        path: `/dashboard/course/create`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Create Course",
      },
    ],
  },
  {
    title: "Category",
    icon: "fe-database",
    type: "sub",
    menusub: true,
    active: false,
    selected: false,
    dirchange: false,
    role: ["Super Admin", "Editor"],
    children: [
      {
        path: `/dashboard/category`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Category List",
      },
      {
        path: `/dashboard/category/create`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Create Category",
      },
    ],
  },
  {
    title: "Property",
    icon: "fe-grid",
    type: "sub",
    menusub: true,
    active: false,
    selected: false,
    dirchange: false,
    role: ["Super Admin", "Editor", "Property Manager"],
    children: [
      {
        path: `/dashboard/property`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Property List",
      },
      {
        path: `/dashboard/property/create`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Create Property",
      },
    ],
  },
  {
    title: "Enquiry",
    icon: "fe-list",
    type: "sub",
    menusub: true,
    active: false,
    selected: false,
    dirchange: false,
    role: ["Super Admin"],
    children: [
      {
        path: `/dashboard/enquiry`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Enquiry",
      },
      {
        path: `/dashboard/enquiry/archive`,
        type: "link",
        active: false,
        selected: false,
        dirchange: false,
        title: "Archived Enquiry",
      },
    ],
  },
  //   {
  //     menutitle: "WIDGETS",
  //   },

  //   {
  //     path: `${import.meta.env.BASE_URL}widgets`,
  //     title: "Widgets",
  //     icon: "fe-grid",
  //     type: "link",
  //     active: false,
  //     selected: false,
  //     dirchange: false,
  //   },

  //   {
  //     menutitle: "GENERAL",
  //   },

  //   {
  //     title: "UI Elements",
  //     icon: "fe-package",
  //     type: "sub",
  //     menusub: true,
  //     active: false,
  //     selected: false,
  //     dirchange: false,
  //     children: [
  //       {
  //         path: `${import.meta.env.BASE_URL}uielements/alerts`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Alerts",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}uielements/badges`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Badges",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}uielements/breadcrumbs`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Breadcrumb",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}uielements/buttons`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Buttons",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}uielements/buttongroups`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Button Group",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}uielements/cards`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Cards",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}uielements/dropdowns`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Dropdowns",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}uielements/imagesfigures`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Images & Figures",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}uielements/listgroups`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "List Group",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}uielements/navtabs`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Navs & Tabs",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}uielements/objectfit`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Object Fit",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}uielements/paginations`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Pagination",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}uielements/popovers`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Popovers",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}uielements/progress`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Progress",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}uielements/spinners`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Spinners",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}uielements/toasts`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Toasts",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}uielements/tags`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Tags",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}uielements/tooltips`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Tooltips",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}uielements/typography`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Typography",
  //       },
  //     ],
  //   },

  //   {
  //     title: "Utilities",
  //     icon: "fe-slack",
  //     type: "sub",
  //     menusub: true,
  //     active: false,
  //     selected: false,
  //     dirchange: false,
  //     children: [
  //       {
  //         path: `${import.meta.env.BASE_URL}utilities/avatars`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Avatars",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}utilities/borders`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Borders",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}utilities/breakpoints`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Breakpoints",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}utilities/colors`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Colors",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}utilities/columns`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Columns",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}utilities/flex`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Flex",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}utilities/gutters`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Gutters",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}utilities/helpers`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Helpers",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}utilities/position`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Positions",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}utilities/additionalcontent`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Additional Contents",
  //       },
  //     ],
  //   },

  //   {
  //     title: "Charts",
  //     icon: "fe-pie-chart",
  //     type: "sub",
  //     menusub: true,
  //     active: false,
  //     selected: false,
  //     dirchange: false,
  //     children: [
  //       {
  //         title: "Apex Charts",
  //         type: "sub",
  //         menusub: true,
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         children: [
  //           {
  //             path: `${import.meta.env.BASE_URL}charts/apexchart/linechart`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Line Charts",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}charts/apexchart/areachart`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Area Charts",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}charts/apexchart/columnchart`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Column Charts",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}charts/apexchart/barchart`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Bar Charts",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}charts/apexchart/mixedchart`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Mixed Charts",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}charts/apexchart/rangeareachart`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Range Area Charts",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}charts/apexchart/timelinechart`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Timeline Charts",
  //           },
  //           {
  //             path: `${
  //               import.meta.env.BASE_URL
  //             }charts/apexchart/candlestickchart`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Candlestick charts",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}charts/apexchart/boxplotchart`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Boxplot Charts",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}charts/apexchart/bubblechart`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Bubble Charts",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}charts/apexchart/scatterchart`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Scatter Charts",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}charts/apexchart/heatmapchart`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Heatmap Charts",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}charts/apexchart/treemapchart`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Treemap Charts",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}charts/apexchart/piechart`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Pie charts",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}charts/apexchart/radialbarchart`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Radialbar Charts",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}charts/apexchart/radarchart`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Radar Charts",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}charts/apexchart/polarareachart`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Polararea Charts",
  //           },
  //         ],
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}charts/chartjs`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Chartjs Charts",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}charts/echart`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "EChart Charts",
  //       },
  //     ],
  //   },

  //   {
  //     title: "Forms",
  //     icon: "fe-file-text",
  //     type: "sub",
  //     badgetxt: "6",
  //     menusub: true,
  //     active: false,
  //     selected: false,
  //     dirchange: false,
  //     children: [
  //       {
  //         title: "Form Elements",
  //         type: "sub",
  //         menusub: true,
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         children: [
  //           {
  //             path: `${import.meta.env.BASE_URL}forms/formelement/input`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Inputs",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}forms/formelement/checkradios`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Checks & Radios ",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}forms/formelement/inputgroup`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Input Group",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}forms/formelement/formselect`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Form Select",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}forms/formelement/rangeslider`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Range Slider",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}forms/formelement/inputmasks`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Input Masks",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}forms/formelement/fileupload`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "File Uploads",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}forms/formelement/datetimepicker`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Date,Time Picker",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}forms/formelement/colorpicker`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Color Pickers",
  //           },
  //         ],
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}forms/floatinglabels`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Floating Labels",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}forms/formlayouts`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Form Layouts",
  //       },
  //       {
  //         title: "Form Editors",
  //         type: "sub",
  //         menusub: true,
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         children: [
  //           {
  //             path: `${import.meta.env.BASE_URL}forms/formeditor/suneditor`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Sun Editor",
  //           },
  //         ],
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}forms/validation`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Validation",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}forms/select2`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Select2",
  //       },
  //     ],
  //   },

  //   {
  //     title: "Advanced Ui",
  //     icon: "fe-file",
  //     type: "sub",
  //     menusub: true,
  //     active: false,
  //     selected: false,
  //     dirchange: false,
  //     children: [
  //       {
  //         path: `${import.meta.env.BASE_URL}advancedui/accordioncollapse`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Accordions & Collapse",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}advancedui/carousels`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "carousel",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}advancedui/cryptocurrencies`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Crypto-currencies",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}advancedui/defaultchat`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Default Chat",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}advancedui/draggablecard`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Draggable Cards",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}advancedui/modalcloses`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Modals & Closes",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}advancedui/navbar`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Navbar",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}advancedui/offcanvas`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Offcanvas",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}advancedui/placeholder`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Placeholders",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}advancedui/ratings`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Ratings",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}advancedui/search`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Search",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}advancedui/swiperjs`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Swiper JS",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}advancedui/userlist`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "User list",
  //       },
  //     ],
  //   },

  //   {
  //     menutitle: "WEB APPS",
  //   },

  //   {
  //     title: "Apps",
  //     icon: "fe-package",
  //     type: "sub",
  //     menusub: true,
  //     active: false,
  //     selected: false,
  //     dirchange: false,
  //     children: [
  //       {
  //         path: `${import.meta.env.BASE_URL}apps/fullcalendar`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Full Calender",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}apps/gallery`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Gallery",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}apps/sweetalerts`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Sweet Alerts",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}apps/timeline`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Timeline",
  //       },
  //     ],
  //   },

  //   {
  //     title: "Pages",
  //     icon: "fe-layers",
  //     type: "sub",
  //     menusub: true,
  //     active: false,
  //     selected: false,
  //     dirchange: false,
  //     children: [
  //       {
  //         path: `${import.meta.env.BASE_URL}pages/profile`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Profile",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}pages/editprofile`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Edit Profile",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}pages/mailinbox`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Mail-Inbox",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}pages/mailcompose`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Mail-Compose",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}pages/aboutcompany`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "About Company",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}pages/services`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Services",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}pages/faqs`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "FAQS",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}pages/terms`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Terms",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}pages/invoice`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Invoice",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}pages/pricingtables`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Pricing Tables",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}pages/emptypage`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Empty Page",
  //       },
  //       {
  //         title: "Blog",
  //         menusub: true,
  //         type: "sub",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         children: [
  //           {
  //             path: `${import.meta.env.BASE_URL}pages/blog/blog`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Blog",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}pages/blog/blogdetails`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Blog Details",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}pages/blog/blogpost`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Blog Post",
  //           },
  //         ],
  //       },
  //       {
  //         title: "E-commerce",
  //         menusub: true,
  //         type: "sub",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         children: [
  //           {
  //             path: `${import.meta.env.BASE_URL}pages/ecommerce/shop`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Shop",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}pages/ecommerce/shoppingdetail`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Shopping Details",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}pages/ecommerce/shoppingcart`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Shopping Cart",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}pages/ecommerce/wishlist`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Wishlist",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}pages/ecommerce/checkout`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Checkout",
  //           },
  //         ],
  //       },
  //       {
  //         title: "File Manager",
  //         menusub: true,
  //         type: "sub",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         children: [
  //           {
  //             path: `${import.meta.env.BASE_URL}pages/filemanager/filemanager`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "File Manager",
  //           },
  //           {
  //             path: `${
  //               import.meta.env.BASE_URL
  //             }pages/filemanager/filemanagerlist`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "File Manager List",
  //           },
  //           {
  //             path: `${import.meta.env.BASE_URL}pages/filemanager/filedetails`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "File Details",
  //           },
  //         ],
  //       },
  //     ],
  //   },

  //   {
  //     title: "Nested Menu",
  //     icon: "fe-sliders",
  //     menusub: true,
  //     type: "sub",
  //     active: false,
  //     selected: false,
  //     dirchange: false,
  //     children: [
  //       {
  //         path: "#/Nested-1",
  //         type: "empty",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Nested-1",
  //       },
  //       {
  //         title: "Nested-2",
  //         type: "sub",
  //         menusub: true,
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         children: [
  //           {
  //             path: "#/Nested-2.1",
  //             type: "empty",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "Nested-2-1",
  //           },
  //           {
  //             title: "Nested-2.2",
  //             type: "sub",
  //             menusub: true,
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             children: [
  //               {
  //                 path: "#/Nested-2.2.1",
  //                 type: "empty",
  //                 active: false,
  //                 selected: false,
  //                 dirchange: false,
  //                 title: "Nested-2-2-1",
  //               },
  //               {
  //                 path: "#/Nested-2.2.2",
  //                 type: "empty",
  //                 active: false,
  //                 selected: false,
  //                 dirchange: false,
  //                 title: "Nested-2-2-2",
  //               },
  //             ],
  //           },
  //         ],
  //       },
  //     ],
  //   },

  //   {
  //     menutitle: "TABLES & AUTHENTICATION",
  //   },

  //   {
  //     title: "Tables",
  //     icon: "fe-clipboard",
  //     type: "sub",
  //     badgetxt: "3",
  //     menusub: true,
  //     active: false,
  //     selected: false,
  //     dirchange: false,
  //     children: [
  //       {
  //         path: `${import.meta.env.BASE_URL}tables/tables`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Tables",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}tables/gridjstables`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Grid JS Tables",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}tables/datatables`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Data Tables",
  //       },
  //     ],
  //   },
  //   {
  //     title: "Authentication",
  //     icon: "fe-settings",
  //     type: "sub",
  //     menusub: true,
  //     active: false,
  //     selected: false,
  //     dirchange: false,
  //     children: [
  //       {
  //         path: `${import.meta.env.BASE_URL}authentication/login`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Login",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}authentication/register`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Register",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}authentication/forgotpassword`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Forget Password",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}authentication/lockscreen`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Lock screen",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}authentication/underconstruction`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Under Construction",
  //       },
  //       {
  //         title: "Error Pages",
  //         type: "sub",
  //         menusub: true,
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         children: [
  //           {
  //             path: `${
  //               import.meta.env.BASE_URL
  //             }authentication/errorpages/error400`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "400",
  //           },
  //           {
  //             path: `${
  //               import.meta.env.BASE_URL
  //             }authentication/errorpages/error401`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "401",
  //           },
  //           {
  //             path: `${
  //               import.meta.env.BASE_URL
  //             }authentication/errorpages/error403`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "403",
  //           },
  //           {
  //             path: `${
  //               import.meta.env.BASE_URL
  //             }authentication/errorpages/error404`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "404",
  //           },
  //           {
  //             path: `${
  //               import.meta.env.BASE_URL
  //             }authentication/errorpages/error500`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "500",
  //           },
  //           {
  //             path: `${
  //               import.meta.env.BASE_URL
  //             }authentication/errorpages/error503`,
  //             type: "link",
  //             active: false,
  //             selected: false,
  //             dirchange: false,
  //             title: "503",
  //           },
  //         ],
  //       },
  //     ],
  //   },

  //   {
  //     menutitle: "MAPS & ICONS",
  //   },

  //   {
  //     title: "Maps",
  //     icon: "fe-map-pin",
  //     type: "sub",
  //     menusub: true,
  //     active: false,
  //     selected: false,
  //     dirchange: false,
  //     children: [
  //       {
  //         path: `${import.meta.env.BASE_URL}maps/leafletmaps`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Leaflet Maps",
  //       },
  //       {
  //         path: `${import.meta.env.BASE_URL}maps/simplemaps`,
  //         type: "link",
  //         active: false,
  //         selected: false,
  //         dirchange: false,
  //         title: "Simple Maps",
  //       },
  //     ],
  //   },

  //   {
  //     path: `${import.meta.env.BASE_URL}Icons`,
  //     title: "Icons",
  //     icon: "fe-command",
  //     type: "link",
  //     active: false,
  //     selected: false,
  //     dirchange: false,
  //   },
];
